filetype off
set nocompatible

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'bling/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'henrik/vim-indexed-search'
"Plugin 'lyuts/vim-rtags'
Plugin 'kopischke/vim-fetch'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'gnattishness/cscope_maps'
Plugin 'kergoth/vim-bitbake'
Plugin 'rlue/vim-barbaric'
Plugin 'mhinz/vim-signify'
Plugin 'edkolev/tmuxline.vim'
let g:tmuxline_powerline_separators = 0

call vundle#end()
filetype plugin indent on

" global preferences "
colorscheme torte
set nu
set t_Co=256
set mouse=a 
set termencoding=utf-8 
set clipboard=unnamedplus
set clipboard=unnamed

" Remember info about open buffers on close
set viminfo^=%

" Backup
set undofile      
set noswapfile
set nobackup

" Sounds
set noerrorbells
set novisualbell

" search 
set smartcase
set ignorecase
set incsearch
set showmatch

" indention
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" highlighting
syntax on
set relativenumber
set hlsearch

filetype indent on

set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
set laststatus=2

set updatetime=100
