autoload -Uz promptinit
promptinit
prompt adam1

# Use modern completion system
autoload -Uz compinit
compinit -u

#history
SAVEHIST=10000
HISTFILE=~/.zsh_history

setopt share_history
setopt histignorealldups
setopt incappendhistory

#bindings
bindkey -v
bindkey '^R' history-incremental-search-backward

#aliases
alias rsp='rsync -vP'

case $(uname) in
    Darwin)
        alias ls='ls -G' ;;
    Linux)
        alias ls='ls --color' ;;
esac
