# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="aphex"


# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(git
vi-mode
zsh-autosuggestions
history-search-multi-word
pip
)

source $ZSH/oh-my-zsh.sh

# User configuration

source "$HOME/utils/git-subrepo/.rc"
fpath=('~/utils/git-subrepo/share/zsh-completion' $fpath)

HISTSIZE=999999999
SAVEHIST=$HISTSIZE
HISTFILE=~/.zsh_history

#setopt share_history
#setopt histignorealldups
#setopt incappendhistory

#aliases
alias rsp='rsync -vP'
alias waf="$PWD/modules/waf/waf-light"
alias ccat='pygmentize -g -O style=colorful,linenos=1'
alias realpath='python -c "import os; import sys; print(os.path.realpath(sys.argv[1]))"'


stty -ixon
